apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - userarn: arn:aws:iam::730335272010:user/github-ci
      username: github-ci
      groups:
        - system:masters
# This config map is used for allowing profile naming github-ci to use kubectl as admin